### ISSUE TITLE
Is there an ODD?

### ISSUE THREAD

**Issue by lb42** [linhd-postdata/disco#1]
The schema at  https://github.com/postdataproject/disco/blob/master/schema/tei_all_DISCO.rnc includes a comment:

` Schema generated from ODD source 2017-09-05T07:09:51Z.` 

But I can't find the ODD source anywhere in your repo. Was the schema in fact made by hand-editing the rnc source of tei all? :-(

**Comment by HelenaSabel** [comment]
Our colleague @morethanbooks began the schema creation process the “right way” so the first version of the schema was indeed generated  from an ODD source. For the second release, we created additional schematron rules and modified the rnc file directly (by hand).
I am opening a second issue in order to create the correct documentation in regards to the current schema. Thank you very much for stopping by ;-)

**Comment by lb42** [comment]
Thanks for the quick response. Don't hesitate to ask if you need help with your ODD!
